<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />

    <link name="base_foot_plane">
    </link>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
            <material name="green" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" l="${base_length}" w="${base_width}" h="${base_height}"
                            xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </link>

    <joint name="base_base_foot_plane" type="fixed">
        <parent link="base_foot_plane" />
        <child link="base_link" />
        
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </joint>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_back_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" h="${wheel_length}" xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
        </link>        
    </xacro:macro>

    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />

    <joint name="base_right_back_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_back_wheel_link" />
        <origin xyz="${- base_length / 4.0} ${- base_width / 2 - wheel_length / 2} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_back_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_back_wheel_link" />
        <origin xyz="${- base_length / 4.0} ${base_width / 2 + wheel_length / 2} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <link name="front_caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius / 2}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius / 2}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:sphere_inertia m="0.5" r="${wheel_radius / 2}" xyz="0 0 0" rpy="0 0 0" />
    </link>
    
    <joint name="base_front_caster_wheel" type="fixed">
        <parent link="base_link" />
        <child link="front_caster_wheel" />
        <origin xyz="${base_length / 3.0} 0 ${- wheel_radius / 2}" rpy="0 0 0" />
    </joint>

</robot>